name: demo
description: A new Flutter demo project.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  package_info: ^0.3.2
  image_picker: ^0.4.1
  fluttertoast: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/small/
    - assets/images/middle/
    - assets/images/large/
  fonts:
    - family: IconFont
      fonts:
        - asset: assets/fonts/iconfont.ttf
